name: todos
description: A Flutter project to manage state with bloclibrary.dev
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^1.0.0
  todos_core:
    path: packages/todos_core

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
