name: todos_core
description: Dart package for todos core.
version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.0.0
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^1.0.2
  very_good_analysis: ^2.4.0
